<!DOCTYPE html>
<head>
  <title>Rental Wise</title>
  <link rel="stylesheet" href="w3/w3.css" />
  <link rel="stylesheet" href="assets/css/bootstrap.min.css"/>
  <link href="assets/font-awesome-4.5.0/css/font-awesome.css" rel="stylesheet" />
  <script src="js/jquery-1.11.2.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <style>
  .lbl{ font-weight: normal !important;}
  .glyphicon-map-marker{color:#8B0000;}
  </style>
</head>

<body>
    <?php include_once('Navbar.htm');  ?>
    <div class="container">
    
    <br /><br />
    <h3>Terms of Service</h3>
    
    <p>     
        The terms are legally binding on you, so it’s important that you read and understand them.
        
        Below are the general terms that apply to all users of the WiseRental (Pty) Ltd (WiseRental) marketplace (“Platform”), as well as those terms that apply specifically to owners and to renters.
        All of the terms stated in these Terms of Service, together with WiseRental’s Privacy Policy and the User Policies provided on the WiseRental site (the “WiseRental Policies”) constitute the “Agreement” between you and WiseRental. WiseRental may change the terms of the agreement from time to time.
        
        As stated on the WiseRental website, when you click the appropriate button to continue with your registration that action will constitute acceptance of the Agreement (“Registering”, “Signing up”). If you have any questions for us concerning the Agreement or WiseRental generally, please contact us at support@WiseRental.co.za
        
        Thank you for registering with WiseRental!
        
    </p>
    
        
     <h3>General Terms</h3>   
     
     <p>  
        The following terms apply to each person who registers on
        the WiseRental platform (“marketplace”):
        
        Registration and Verification. When you sign-up for the services offered by WiseRental, you will provide certain information about yourself (e.g. information concerning your car, your driving record, etc.). You promise to provide complete and accurate information to WiseRental. WiseRental may use third party services to verify the information you provide to us and to obtain additional related information and corrections where applicable and you hereby authorize WiseRental to request, receive, use and store such information for a reasonable period of time. WiseRental may accept or reject your registration application at its discretion for any reason. Before a car goes out on rental it is the responsibility of the owner to make sure a renter’s driver’s license has been verified by WiseRental. Driver’s licenses must also be verified once the renter picks up the vehicle from the car owner to make sure the renter’s driver’s license is still valid and the person is who they say they are. If a Driver’s License is not verified by an Owner WiseRental cannot accept responsibility for renters driving without a valid driver’s license.
        On-going Information Updates. You promise to update the information you have provided to WiseRental in the event of any changes to your driving record or contact information. These updates must be made on the website by the member themselves when there is any change in information previously provided. Specifically, with respect to your contact information, WiseRental may deliver notices to you at the most recent email and billing address provided by you, and those notices will be considered valid even if you no longer maintain the email account, the phone number, or receive mail at that address. Also, you are and will be solely responsible for all of the activity that occurs through your account, so please keep your password and account information secure. WiseRental may use and share your information as described in our Privacy Policy.
        Incorporation of Additional Terms. WiseRental User Policies provide additional terms of use of the WiseRental marketplace and are legally binding and are hereby incorporated into this Agreement. In addition, the WiseRental Privacy Policy will apply to all of the activities described in this Agreement and is hereby incorporated into this Agreement. Please review these documents carefully. If you have any questions concerning those Policies, please contact us at support@WiseRental.co.za.
        Your Commitments. You agree that you will always use the marketplace in compliance with the terms of this Agreement and any other policies and standards provided to you by WiseRental. You promise WiseRental that you have the legal right to enter into this Agreement and to use the marketplace. You promise that your activities with WiseRental will not violate anyone else’s rights. You also agree to comply with all applicable laws and regulations of South Africa.
        Protection. In addition to the terms set forth in Sections 17 and 30 below, during the applicable rental period (i.e. “the scheduled start time of renter’s reservation”, “booking” through to their return of the car to the owner), WiseRental will provide certain comprehensive and collision protection insurance for the car, as well as liability insurance for bodily injury and property damage arising from use of the car. The liability insurance and the comprehensive and collision protection shall be excess and contingent over any other valid and collectible insurance that may be available to the renter. Insurance amounts and other details may be found in the WiseRental User Policies. Car owners do not need to take out any additional insurance during the applicable rental period.
        Termination. You may discontinue your use of the WiseRental marketplace at any time and WiseRental may terminate your access to the WiseRental marketplace for any reason or no reason. Termination of access to the marketplace will not release either party from any obligations incurred prior to the termination and WiseRental may retain and continue to use for its own internal purposes any information previously provided by you. Termination of this Agreement will not have any effect on the disclaimers, waiver or liability limitations provided under this Agreement and all of those terms will survive any termination of this Agreement. No cancellation fees will be charged to any WiseRental marketplace users for terminating their account.
        Disclaimer of Warranty and Limitation of Liability. This Agreement describes all of WiseRental’s obligations in the event of any loss or damage resulting from your participation in the marketplace. In order to disclaim warranties and to provide for certain limitations on our liability, we are required to provide the following information in this format:
        WiseRental PROVIDES A MARKETPLACE THAT ENABLES CAR RENTAL SERVICES BETWEEN CAR OWNERS AND CAR RENTERS. WiseRental DOES NOT PROVIDE CAR RENTAL SERVICES AND IS NOT RESPONSIBLE FOR ANY OF THE ACTS OR OMISSIONS OF ANY OF THE USERS OF ITS MARKETPLACE, THE CAR MANUFACTURER OR ANY THIRD PARTY PROVIDER OF SERVICES (E.G. IN-CAR GPS OR OTHER SYSTEMS). EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT, WiseRental HEREBY DISCLAIMS ANY WARRANTY OF ANY KIND WITH RESPECT TO THE CARS AND OTHER PRODUCTS AND SERVICES PROVIDED BY OR THROUGH WiseRental, WHETHER SUCH WARRANTIES ARE EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. WiseRental MAKES NO WARRANTY THAT THE SERVICE WILL BE UNINTERRUPTED OR SECURE OR THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED. USE OF THE SERVICE AND ANY CARS RENTED THROUGH THE MARKETPLACE IS AT YOUR OWN RISK. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM WiseRental WILL CREATE ANY EXPRESS WARRANTY.
        
     </p>
     <p>
        IN NO EVENT WILL WiseRental BE LIABLE TO YOU FOR INDIRECT, CONSEQUENTIAL, EXEMPLARY, SPECIAL OR INCIDENTAL DAMAGES EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OTHER THAN WiseRental’S INSURANCE AS
        DESCRIBED IN THIS AGREEMENT, WiseRental’S LIABILITY UNDER THIS AGREEMENT, WHETHER BASED ON BREACH OF WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, WILL IN NO EVENT EXCEED THE AMOUNT OF THE RENTER’S DEPOSIT AMOUNT. WiseRental IS NOT LIABLE FOR OUTSTANDING DEBT OWED TO OWNERS. ANY ADDITIONAL FEES OWED TO THE OWNER EXCEEDING THE RENTER’S DEPOSIT AMOUNT WILL BE HANDED OVER TO WiseRental’S APPOINTED DEBT COLLECTION AGENCY AND ANY FUNDS RECEIVED THROUGH THIS AGENCY WILL BE PAID OVER TO THE OWNER OF THE VEHICLE.
        
        No Agency. WiseRental does not intend to appoint you or any other member as its employee, legal agent or to form any kind of legal partnership or joint venture. You are not authorized to make any commitments on behalf of WiseRental and WiseRental will not make commitments on your behalf, except as contemplated by the marketplace or expressly stated in this Agreement.
        No License. The WiseRental marketplace contains copyrighted material, trademarks, and other proprietary information, all of which is individually and collectively protected by copyright laws and other intellectual property laws in South Africa and internationally. Except as part of the intended use of the WiseRental marketplace, you must not copy, distribute, make available, publicly perform, display or create any work based on such content, or exploit such content in any way, in whole or in part. Except for content provided by users through the WiseRental marketplace, WiseRental and its licensors own all of the content presented through the WiseRental marketplace. All rights are hereby expressly reserved.
        General. This Agreement states the entire understanding between you and WiseRental concerning your participation in the marketplace and supersedes any verbal or written communications between us. You may not delegate your legal obligations or transfer any of your rights in whole or in part to any third party without advance written consent of WiseRental. You will remain responsible for your obligations hereunder in any event. If any provision of this Agreement is construed to be unenforceable, the remaining provisions will not be affected and will continue in full force and effect. WiseRental must agree to any modification or waiver of any term of this Agreement in writing. WiseRental’s failure to exercise any right under this Agreement will not constitute a waiver of any other right WiseRental may have. This Agreement and any related claims or disputes would be governed by and construed in accordance with the laws of South Africa.
        Vehicle Pick-up and Drop-off. Renters must meet the vehicle owner or a person appointed by the vehicle owner at the start of their rental period and at a pre-agreed location. Vehicle deliveries may also be organized by the Car Owner to the renter for which Car Owners will charge a fee relative to the distance covered. All delivery charges must be discussed with renters before delivery commences. At the pickup and at the drop off of the car, the trip checklist needs to be signed by both parties. If you don’t sign the trip checklist, we may assume that the trip checklist sent to us by the owner is true. If you don’t agree with the trip checklist, please add this to the form, still sign the trip checklist and send us photographic proof within 24 hours after the end of the rental. Together with the trip checklist, photographic proof needs to be submitted within 24 hours after the end of the rental. Quotes and receipts must be submitted within 7 days after the end of the rental. At the end of their trip, renters must return the car and the keys to the owner at a pre-agreed location.
         
    </p>    
        <h3>Terms for Renters</h3>
      
      <p>  
        The following Sections 12-22 apply if you rent a car using the WiseRental marketplace:
        
        Information provided to WiseRental. As part of establishing and maintaining your status as an authorized renter through the WiseRental marketplace, you will need to provide certain information about yourself and your driving record. You understand and agree that you must meet the eligibility requirements at all times that you use a car through the marketplace; if, after initial approval, you later fail to meet the eligibility requirements (e.g., you have a subsequent driving violation that would make you ineligible), you are required to inform us of the change in status, and refrain from renting or driving cars via WiseRental. As stated in Section 1 above, you have authorized WiseRental to obtain your driving record and other applicable reports at any time, in order to verify that you meet the eligibility requirements of the marketplace. You understand and agree that WiseRental may periodically request additional verification of eligibility and proper verification of usage from you as a renter and that if you fail to provide satisfactory evidence of your continued compliance with this Agreement, WiseRental may terminate your membership immediately. WiseRental may, subject to the terms of this Agreement and the Privacy Policy, retain and continue to use, for its own internal purposes, any information previously provided by you. All of your information will be held and treated in accordance with the Privacy Policy. Please note, any failure to disclose car-related violations, accidents or other material information is grounds for immediate rejection or termination of your membership, effective as of such failure.
        Fees and Losses. You authorize WiseRental to charge any payment cards recorded on your account for all amounts due, including but not limited to, security deposits, admin fees, processing fees, usage fees, fines/penalties, deductibles, and damages, and you furthermore represent and warrant that you have the right to make this authorization. You will be responsible for payment of usage fees from the start of your rental period until the time you return the car. You will be responsible for all of the costs relating to any citations and fines (e.g. tolls, parking tickets, towing fees, admin fees) incurred during the rental. 
        In addition, WiseRental’s protection may not be available to you in the event you breach your obligations under this Agreement (e.g. if you drive a vehicle while under the influence of drugs or alcohol or otherwise violate any of the WiseRental User Policies). Subject to the coverage and protection available to you, you acknowledge that you are fully responsible for any damage, losses or other liabilities relating to your rental activities through the WiseRental marketplace. You agree that in the event damage is reported, WiseRental may immediately charge you up to the amount of R5000 insurance excess as stipulated when you booked the car. During the applicable rental period (i.e., “the scheduled start time of renter’s reservation”, “booking” through to their return of the car to the owner), the renter is liable for the excess payment of R5000 regardless of whether the accident/loss was caused by a 3rd party. Nothing in this Agreement is intended to limit your responsibilities or WiseRental’s legal rights in connection with your use of the marketplace (or any vehicles rented through the marketplace).
        </p>
        
        <p>
        The renter gives authority to WiseRental to charge for any additional damage or costs as set out in this agreement that exceeds the deposit amount paid by the renter to their card/payment method used for their car rental payment on WiseRental’s partner’s website (www.vcs.co.za) to process the payment.
        </p>
        
       <p> 
        You acknowledge that WiseRental requires and hold a deposit as part of the car rental and that WiseRental will return this deposit 15 days after the end of the rental period if no new rentals have been activated by the renter during this period and if there were no additional costs the renter was liable for as stipulated in this agreement e.g. insurance excess, damage to vehicle, extra kilometers, cleaning fees, missing fuel, delivery charges, etc.
        </p>
        
        <p>
        When a renter wishes to extend their current rental period and there are any outstanding amounts against the renter’s account, WiseRental will require the renter to top up their deposit amount so that the renter has paid for a full deposit at the start of their extended rental period.
        </p>
        
        <p>
        Use of the Car. When you rent a car through WiseRental, you may use the car only for your personal use and not for any commercial purposes (e.g. running a taxi service). You may not access a car until the beginning of your rental period and you must return the car on time and to the correct location. You must exercise reasonable care in your use of the car. In the event WiseRental has any concern about your use of a vehicle, WiseRental may terminate your reservation at its discretion at any time and require the return of the vehicle, including recovering the vehicle on behalf of the owner. You are required to wear seat belts during the operation of the car and to require that all of your passengers wear seatbelts as well. You are also required to meet any laws or regulations concerning car seats and other protections for young passengers.
        The WiseRental User Policies provide a list of Prohibited Uses of any car rented through the WiseRental marketplace. The list isn’t meant to be exhaustive. If you have any concerns about your planned use, please contact WiseRental customer service at support@WiseRental.co.za. You will be fully responsible for any claims, loss or damage related to your misuse of a car. Renters also acknowledge that using a vehicle in a prohibited manner may nullify insurance coverage and may furthermore nullify any comprehensive insurance or collision protection.
        </p>
        
        <p>
        Condition of the Car. You understand that, unless otherwise specifically noted, the cars offered through the WiseRental marketplace are owned by third parties and are not owned or maintained by WiseRental. Each owner is responsible for maintaining and repairing the car(s) they offer through the marketplace in a roadworthy condition and is ultimately responsible for the condition of the car during the rental period. Please complete a visual inspection of any rented car before you begin your use of the car. If you find damage in your initial inspection, you must notify WiseRental immediately to avoid any confusion about your role in the cause of the damage, or you may be held liable for any damage. The renter and the owner must download the ‘Trip Checklist’ from WiseRental’s website and jointly agree and document such agreement, with supporting photographs, of any pre-existing damage for which you as the renter should not be liable. The ‘Trip Checklist’ must again be completed by the owner and the renter at the end of the rental period to assess if any new damage has occurred during the rental period. If any new damage is recorded the ‘Trip Checklist’ must be signed by both owner and renter and send to support@WiseRental.co.za within 24 hours after the end of the rental period. The owner has the right to send WiseRental proof of any new damaged discovered 24 hours after the vehicle has been returned. If you find damage on your initial inspection and fail to report it on the ‘Trip Checklist, WiseRental may assume that the damage occurred during your rental period. If, after your initial inspection, you believe that the car is not safe enough to drive, please do not use the car; in that event, please contact the WiseRental team immediately.
        Incident Reporting. You must immediately report any damage to the car you are using to WiseRental at support@WiseRental.co.za and if there has been a collision, to the police as well. When a report is made to the police the case number of the police report must also be forwarded to support@WiseRental within 24 hours of the accident. You will need to use all reasonable efforts to secure evidence from any available witnesses and to provide WiseRental with a written description of the incident and any other information WiseRental may request, including identity and insurance information of any parties involved in the incident. You are also required to cooperate in any loss investigation conducted by WiseRental, our claims administrators, or insurers. After an incident, you may not continue to use the car unless you have the explicit permission of WiseRental or the car owner. Failure to timely report an incident may reduce or invalidate the comprehensive insurance from WiseRental.
        Insurance. In addition to the terms in Section 5 above: You understand and agree that WiseRental will provide primary liability insurance for the owner and that renters will not look to an owner’s policy for coverage in accordance with WiseRental Policies.
        WiseRental will provide certain liability insurance and protection against physical damage losses as described in this Agreement and the WiseRental User Policies. You are fully responsible for paying any damages and excesses not covered by insurance, as well as insurance deductibles, fees, expenses, liens, and fines arising out of your use of a car on the WiseRental platform. If WiseRental advances any payment on your behalf, you will continue to be responsible for such amounts and will adhere to WiseRental’s schedule for repayment of those amounts to WiseRental.
        </p>
        
        <p>
        The renter is liable up to the amount of R5000 per insurance claim. If there is more than one claim (more than one incident) on the car the renter will be liable for the additional claim as well and an additional excess amount of R5000. If the renter’s deposit has been depleted through the use of an insurance claim or any other claims against the renter e.g. excess kilometers the renter will be liable for all additional charges as well.
        </p>
        
        <p>
        Refund Policy. The renter will be charged for the full reservation cost regardless of when you return the car. If the vehicle becomes inoperable during the rental period and cannot be fixed within 1 day or a reasonable time frame agreed upon by the owner and renter, the renter will be refunded for the remainder of the rental period and in the process discontinue the use of the vehicle. A refund will be made within 48 hours after the booking has been canceled.
        Waiver. WiseRental provides a marketplace to allow car owners and renters to connect in an easy and efficient way. Except as expressly provided in this Agreement, WiseRental and the applicable car owner do not accept liability with respect to your use of the WiseRental marketplace or the applicable car(s). AS SUCH, YOU WAIVE ANY AND ALL RIGHTS YOU HAVE TO SUE OR MAKE CLAIMS AGAINST WiseRental AND ITS RESPECTIVE DIRECTORS, OFFICERS, AGENTS, OR EMPLOYEES (THE “WiseRental PARTIES”) AND THE CAR OWNER FOR ANY DAMAGES OR LOSSES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THIS MARKETPLACE INCLUDING, WITHOUT LIMITATION, A CAR NOT BEING AVAILABLE WHEN IT WAS SUPPOSED TO BE, ANY MALFUNCTION OF OR DEFICIENCY IN A CAR, ANY BREACH OF WARRANTY OR OTHER OBLIGATION BY ANY MANUFACTURER OR OTHER THIRD PARTY, ANY PERSONAL INJURY OR PROPERTY DAMAGE SUFFERED BY YOU OR ANY OF YOUR PASSENGERS AND, IN THE CASE OF THE WiseRental PARTIES, ANY ACTIONS OR INACTION OF THE CAR OWNER. YOUR WAIVER DOES NOT EXTEND TO ANY DAMAGES OR LOSSES RESULTING FROM ANY PARTY’S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT.
        I understand and agree that if without lawful cause the car is not returned on expiry of the rental period, the car may be regarded as stolen and criminal charges may be laid with the South African Police services without further notification to me.
        I accept the address set out as my Domicilium citandi et executandi for the service of any legal process. In the event of any legal action being instituted against me for recovery of any amount whatsoever, I shall be liable for all legal costs incurred including, admin costs, 10% receipting fee on each installment paid. If the matter is defended, I will be liable for legal costs incurred on an attorney/client scale. Once my account has been handed over there will be no further correspondence entered into with WiseRental. All correspondence will be with WiseRental’s appointed debt collection agency. I the undersigned, hereby choose my address as I stated on the WiseRental website as my domicilium citandi et executandi for all purposes under this agreement.
        By my signature hereunder I accept that I am liable jointly and severally for the payment of all amounts due to WiseRental in term of or pursuant to the rental agreement. I confirm that if payment hereunder is paid by credit card or charge card, my electronic signature shall constitute authority to debit my nominated credit card or charge card with the total amount due.
        </p> 
        
        <h3>
        Terms for Owners </h3>
        <p>
        The following Sections 23-32 apply if you rent out your car through the WiseRental marketplace:
        </p>
        
        <p>
        Information Given at Registration. When you sign-up for WiseRental, you will identify a particular passenger car(s) that you want to list for rent through the marketplace. Each car must meet the requirements provided by WiseRental on the WiseRental site from time to time. You may only use the marketplace in connection with cars that you own or otherwise have all the necessary rights and permissions to rent out.
        Car Availability. Once you accept a reservation and it is booked, you are required to make the car available as expected by the renter. You must also include the location of the car on your profile page and ensure that the car is available at that location at the beginning of the rental period.
        Rental Fees. You will have the ability to set and revise the vehicle’s rental rates as you choose. WiseRental will pay you the amount collected from those who rent your car, net of the applicable fees payable to WiseRental, as well as any taxes or similar charges that WiseRental collects. You acknowledge that WiseRental’s fees may change from time to time. The fees that apply to you will be the same as posted on the WiseRental website at the time of the applicable rental. Payment to the owner from WiseRental will be initiated on the 25th of the month and will include all relevant amounts earned from the 20th of the previous payment month up until the 19th of the current payment month; provided that WiseRental may impose reasonable minimums for each payment. To the extent you owe WiseRental money for any reason, WiseRental also reserves the right to deduct those amounts from your payment. Please note that you are fully responsible for all taxes relating to or arising out of your activities under this Agreement. WiseRental will need certain information from you to ensure we can report income paid to you as required by law. WiseRental may withhold payments until we have received that information from you.
        Refund Policy. If the vehicle becomes inoperable during the rental period and cannot be fixed within 1 day or a reasonable time frame agreed upon by the owner and renter, the renter will be refunded for the remainder of the rental period, from the moment the vehicle became inoperable, and in the process discontinue the use of the vehicle.
        Maintenance. You are required to regularly check your car for any defects in its operations or safety and have your car inspected as described here. You promise that, at all times, your car will be in safe and roadworthy condition, in good mechanical condition, and in full compliance with all applicable inspection and registration requirements. You agree to respond to any recall or similar safety notices and to complete any recommended action promptly. If WiseRental believes that your car does not conform to reasonable standards, WiseRental will notify you and reserves the right to refrain from listing your car on the marketplace until its concerns have been resolved.
        Decals. WiseRental may, from time to time and at its expense, require that certain labels or other markings, be temporarily affixed to your car while you participate in the marketplace. WiseRental will provide instructions for removal of those labels or decals in connection with any termination of your participation in the marketplace.
        Event Reporting. If you believe that a renter has caused any damage to your car, you are required to document this damage, with the renter, on the “Trip Checklist” that was used to record outgoing damage at the start of the rental. Any new damage must be recorded on the “Trip Checklist” and signed by both renter and owner in order to qualify for cover. The “Trip Checklist” must be sent, signed or not signed, to support@WiseRental within 24 hours after the return of the vehicle. In any event, with each break in a rental activity, you need to inspect your car and report any damage that you believe was caused by a renter. Based on its investigation, WiseRental will reasonably determine whether the damage was caused in the course of the renter’s use of the car. If it was, WiseRental will reimburse you for the loss as described in Sections 30 and 31 below. If WiseRental is not given prompt notice as described in this paragraph, or if you do not provide reasonable cooperation in our investigation, we may not be able to determine the cause and will decline any financial responsibility for such damage.
        Physical Damage. Subject to all of the terms of this Agreement, during each rental period, WiseRental’s insurance will bear the risk of theft, destruction or damage with respect to your car. In the event of a loss that is covered by this Agreement, WiseRental’s insurance will request at least three insurance quotations for damage to your vehicle as covered by this agreement and will pay the expenses of the lowest of the three quotations once approved by WiseRental’s insurance agent, if that amount is greater than the actual market value of your car, pay you the actual market value as determined by WiseRental’s insurance agent. If WiseRental’s insurance agent is not satisfied with the quotations as received by the owner the insurance company may send its assessor to assess the true cost of the damage in question. Note, if WiseRental chooses to pay you the determined market value for your car, you will be required to transfer title to the car to WiseRental or its insurance agent.
        WiseRental will retrieve the cost of the damage from the renter and if the renter’s deposit is depleted we will invoice the renter for the cost of repairs. If the renter refuse to pay or we are unable to retrieve the funds from the renter we will use WiseRental’s appointed debt collection agency to retrieve the funds from the renter. Any amounts retrieved this way from the renter will be paid forward to the car owner. WiseRental will not be liable for outstanding funds that could not be retrieved from a renter.
        </p>
        
        <p>
        There are some exceptions to WiseRental’s obligations under this Section: WiseRental is not responsible for any personal property, including any after-market installations (e.g. equipment racks) that is taken from your car or damaged during a rental period. We recommend that you remove all personal property before making the car available for a reservation. In addition, you should expect normal wear and tear on your car, including minor scrapes and dings, in connection with your participation in the marketplace. WiseRental will not reimburse you for normal wear and tear to your car or when mechanical or electrical functions of the car became inoperable during the rental e.g. electric windows, aircon, lights etc.
        </p> 
        
        <p>
        Other Insurance and Legal Matters. In addition to the terms provided in Section 5 above, you agree to comply with any and all applicable laws and regulations. More information is available in our FAQs. With respect to any insurance policy procured by WiseRental for your benefit, you hereby appoint WiseRental as your attorney-in-fact solely for the purpose of filing claims, receiving payment and otherwise administering that policy. As part of your participation in the marketplace, you do not have to maintain your own insurance. You must inform WiseRental promptly in the event information as previously provided changes. Except with respect to losses to be paid by WiseRental as described above, you will be fully responsible for any losses or damages suffered by any party as the result of your activities under this Agreement.
        Waiver. WiseRental provides a marketplace to allow car owners and renters to connect in an easy and efficient way. Except as expressly provided in this Agreement, WiseRental and the applicable car renter do not accept liability with respect to your use of the WiseRental marketplace. AS SUCH, YOU WAIVE ANY AND ALL RIGHTS YOU HAVE TO SUE OR MAKE CLAIMS AGAINST WiseRental AND ITS RESPECTIVE DIRECTORS, OFFICERS, AGENTS, OR EMPLOYEES (THE “WiseRental PARTIES”) AND THE CAR RENTERS FOR ANY DAMAGES OR LOSSES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THIS MARKETPLACE INCLUDING, WITHOUT LIMITATION, A CAR NOT BEING AVAILABLE WHEN IT WAS SUPPOSED TO BE, IN THE CASE OF THE WiseRental PARTIES, ANY ACTIONS OR INACTION OF THE CAR RENTER.                                              
        Vehicle Returns and Pickups. It is the responsibility of the owner to report to WiseRental if a vehicle was not returned on the last day of the rental period which will be up to the last day the renter paid for. WiseRental will not be responsible for rental charges if the vehicle was not reported as being returned to the owner. WiseRental will not be responsible for any liability if the vehicle is damaged after the last day of the renter’s rental period where the owner did not report to WiseRental the car was not returned by the renter. WiseRental is not responsible for any rental charges or take any liability if an owner hands over a vehicle to a renter if the renter did not pay for the rental yet. The owner will receive an email and SMS from WiseRental to confirm that the renter has paid for the car before the renter will be able to take possession of the car. Owners must check the renter’s driver license in order to confirm the identity of the renter. WiseRental will not be liable for cars that were handed over to a person that is not the renter.
 
        </p>
        <p>
        
    For owners using the WiseRental Plus vehicle management service the following additional Terms of Services apply:
    
    Vehicles left at the premises of our WiseRental Plus vehicle management service must still be under the insurance policy of the owner for the duration the vehicle is under the partner’s care. Only when the vehicle goes out on rental it will be added to WiseRental’s comprehensive insurance policy covering damage or theft.
    WiseRental’s partner’s management of our WiseRental Plus vehicle management service is not responsible for any loss or damage of vehicles left in their care. Our partners will make sure that all vehicles in their care are looked after to the best of their abilities and will keep the vehicles at gated lockable premises.
    WiseRental’s Vehicle Management Service (WiseRental Plus) includes the following services:
    * 24/7 Secure parking
    * Accepting rental requests
    * Getting the car ready for collection
    * Communication with the renter
    * Handing over the keys
    * Filling out the trip checklist
    * Responding to renter problems during rental
    * Responding to car breakdowns
    * Meeting the renter for car returns
    * Filling out the return trip checklist
    Extras:
    * Refueling the vehicle (cost of fuel not included in the price)
    * Cleaning of vehicle (cost of cleaning not included)
    * Damage Repairs (cost of repairs not included)
    * Services: tire, brakes ext. (cost of service not included)
    * Pickup & Delivery Service (cost of delivery service not included)
    Commission Structure
    * Owner receives 55% of the total rental income
        </p>
    </div>
</body>
</html>